/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PROYECTO_2_PRIVATE_H
#define PROYECTO_2_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"ManuelSQ"
#define FILE_VERSION	"1.0.0.0"
#define FILE_DESCRIPTION	"Juego de carreras"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"manuelsq2019"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Cars"
#define PRODUCT_NAME	"Cars 10000"
#define PRODUCT_VERSION	"1.0.0.0"

#endif /*PROYECTO_2_PRIVATE_H*/
